### PR TITLE
Enable google_prettify

### PR DESCRIPTION
**Pull request by wzpan**
Hello,
I found google_prettify dosen't work when I use ruhoh 2.1.1. After working on this issue for a while, I was able to find out that the preblem was caused by the commit [Move google_prettify](https://github.com/ruhoh/ruhoh.rb/commit/fdeff636da2ec2deb3ce239651c2e52da7883df7#system/widgets) at the project ruhoh.rb after Moving google_prettify into a subdirectory to allow for a unified syntax highlighting widget. 

After the change by that commit, the name of the widget was changed. However, the corresponding references in `config.yml` and the `layout/default.html` are not updated synchronously. 

So I fix the problem to enable google_prettify again.

### CODE REVIEW

**Comment by plusjade** [comment]
Thank you for bringing this to my attention! This was a regression in the gem itself so I have fixed it there: https://github.com/ruhoh/ruhoh.rb/commit/757a99f737052817c79e8020ef7f0b73c1718cd6

Thank you also for your pull request but you can see you accidentally also commited changes to your personal blog so I wouldn't be able to accept it either way =P

**Comment by plusjade** [comment]
P.S. this fix is in v2.2 so you'll need to `bundle install` for the latest release.

**Comment by wzpan** [comment]
```
Thank you also for your pull request but you can see you accidentally also commited changes to your personal blog so I wouldn't be able to accept it either way =P
```

Oh that's so strange! I make my own change only after asking this pull request! git 1.8.3 is so weird!

**Comment by plusjade** [comment]
> Oh that's so strange! I make my own change only after asking this pull request! git 1.8.3 is so weird!

Pull Requests are asking for _some branch_ to be merged in with _some other branch_. As you make more commits to the branch in question, those commits reflect in the pull request because the pull request cares about the _branch_ not the commits specifically.

Actually it is a feature since users may discuss the pull request and make updates in order to get it to an acceptable state. 

If you don't intend to pollute the branch in question, just make a separate branch to do your pull request then branch off the branch again and continue working =P

Hope that helps!

**Comment by wzpan** [comment]
<blockquote>
Pull Requests are asking for some branch to be merged in with some other branch. As you make more commits to the branch in question, those commits reflect in the pull request because the pull request cares about the branch not the commits specifically.
Actually it is a feature since users may discuss the pull request and make updates in order to get it to an acceptable state.
Pull Requests are asking for some branch to be merged in with some other branch. As you make more commits to the branch in question, those commits reflect in the pull request because the pull request cares about the branch not the commits specifically.
Actually it is a feature since users may discuss the pull request and make updates in order to get it to an acceptable state.
If you don't intend to pollute the branch in question, just make a separate branch to do your pull request then branch off the branch again and continue working =P
Hope that helps!
If you don't intend to pollute the branch in question, just make a separate branch to do your pull request then branch off the branch again and continue working =P
Hope that helps!
</blockquote>

Thank you for your explanation. That's very very helpful!
I found it still better to update the `config.yml` and `default` layout. So this time I will ask for a pull request for a new branch call `issue12`. Hope this time I will give a clean push! :smile:

**Pull request closed without merging**
